# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# Functions and Ref/Vars ============================================================================================

references:

base_image: &base_image
  hashicorp/terraform:light

working_directory: &working_directory
  ~/example

default_config: &default_config
  docker:
    - image: *base_image
  working_directory: *working_directory
  environment:
    BASH_ENV: /root/.bashrc

repo_cache_key: &repo_cache_key
  v1-repo-{{ .Branch }}-{{ .Revision }}

# Step to restore repository from cache
restore_repo: &restore_repo
  restore_cache:
    key: *repo_cache_key

save_repo: &save_repo
  save_cache:
    key: *repo_cache_key
    paths:
      - *working_directory

set_terraform_environment: &set_terraform_environment
  run:
    name: Configure terraform environment
    command: |
      cd && touch $BASH_ENV
      if [ "${CIRCLE_BRANCH}" == "master" ]; then
        echo 'export TERRAFORM_ENVIRONMENT=production' >> $BASH_ENV
        export AWS_ACCESS_KEY_ID=${awsa}
        export AWS_SECRET_ACCESS_KEY=${awss}
        export AWS_DEFAULT_REGION="us-west-1"
      else
        echo 'export TERRAFORM_ENVIRONMENT=staging' >> $BASH_ENV
        # export AWS_ACCESS_KEY_ID="awsa$"
        export AWS_ACCESS_KEY_ID=${awsa}
        # export AWS_SECRET_ACCESS_KEY="awss$"
        export AWS_SECRET_ACCESS_KEY=${awss}
        export AWS_DEFAULT_REGION="us-west-1"
      fi

terraform_init: &terraform_init
  run:
    name: terraform init
    command: |
      source $BASH_ENV
      cd environments/$TERRAFORM_ENVIRONMENT
      terraform init

apply_job: &apply_job
  <<: *default_config
  steps:
    - *restore_repo
    - *set_terraform_environment
    - *terraform_init
    - attach_workspace:
        at: *working_directory
    - run:
        name: terraform apply
        command: |
          source $BASH_ENV
          cd environments/$TERRAFORM_ENVIRONMENT
          terraform apply --auto-approve ../../terraform.plan

# End Functions and Ref/Vars ============================================================================================

jobs:

# Packer ============================================================================================

  validate:
    docker:
      - image: hashicorp/packer:latest
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate base
          command: packer validate ./packer/packer.json
      # - run:
      #     name: Validate snowflake
      #     command: packer validate ./snowflake/snowflake.json

  build-base:
    docker:
      - image: hashicorp/packer:latest
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Build base
          command: ./scripts/build.sh base ./packer/packer.json
          no_output_timeout: 30m
      - persist_to_workspace:
          root: .
          paths:
            - manifest-base.json
      - store_artifacts:
          path: manifest-base.json

# END Packer ============================================================================================

# Terraform ============================================================================================

  build:
    <<: *default_config
    steps:
      - checkout
      - *set_terraform_environment
      - run:
          name: terraform fmt
          command: |
            source $BASH_ENV
            cd environments/$TERRAFORM_ENVIRONMENT
            if [ $(terraform fmt | grep -v .terraform | tee fmt_result.txt | wc -l) -gt 0 ]; then
              echo "Format of this terraform files is not appropiate:"
              echo
              cat fmt_result.txt
              rm fmt_result.txt
              git checkout -- .
              echo
              echo "Please run terraform fmt"
              exit 1
            fi
      - *save_repo

  plan:
    <<: *default_config
    steps:
      - *restore_repo
      - *set_terraform_environment
      - *terraform_init
      - run:
          name: terraform plan
          command: |
            source $BASH_ENV
            cd environments/$TERRAFORM_ENVIRONMENT
            terraform plan -out=../../terraform.plan
      - persist_to_workspace:
          root: *working_directory
          paths:
            - terraform.plan

  apply:
    <<: *apply_job
  apply-with-approval:
    <<: *apply_job

workflows:
  version: 2
  build_plan_approve_apply:
    jobs:
      - build
      - plan:
          requires:
            - build
      - approve:
          type: approval
          requires:
            - plan
          # filters:
          #   branches:
          #     only: staging
              # only: master
      - apply-with-approval:
          requires:
            - approve
          filters:
            branches:
              only: master
      - apply:
          requires:
            - plan
          # filters:
          #   branches:
          #     only: staging

# END Terraform ============================================================================================
